In [47]:
import pandas as pd

In [48]:
sample = pd.read_json('dataset.json')

In [49]:
sample

                  type                                           features
0    FeatureCollection  {'type': 'Feature', 'properties': {'WARD_NO': ...
1    FeatureCollection  {'type': 'Feature', 'properties': {'WARD_NO': ...
2    FeatureCollection  {'type': 'Feature', 'properties': {'WARD_NO': ...
3    FeatureCollection  {'type': 'Feature', 'properties': {'WARD_NO': ...
4    FeatureCollection  {'type': 'Feature', 'properties': {'WARD_NO': ...
..                 ...                                                ...
193  FeatureCollection  {'type': 'Feature', 'properties': {'WARD_NO': ...
194  FeatureCollection  {'type': 'Feature', 'properties': {'WARD_NO': ...
195  FeatureCollection  {'type': 'Feature', 'properties': {'WARD_NO': ...
196  FeatureCollection  {'type': 'Feature', 'properties': {'WARD_NO': ...
197  FeatureCollection  {'type': 'Feature', 'properties': {'WARD_NO': ...

[198 rows x 2 columns]

In [50]:
df = pd.json_normalize(sample['features'])

In [51]:
df.head(5)

,type,properties.WARD_NO,properties.WARD_NAME,properties.MOVEMENT_ID,properties.DISPLAY_NAME,geometry.type,geometry.coordinates
0,Feature,2,Chowdeswari Ward,1,"Unnamed Road, Bengaluru",MultiPolygon,"[[[[77.5922939, 13.0971962], [77.5909447, 13.0..."
1,Feature,3,Atturu,2,"9th Cross Bhel Layout, Adityanagar, Vidyaranya...",MultiPolygon,"[[[[77.5686203, 13.1270495], [77.5706371, 13.1..."
2,Feature,4,Yelahanka Satellite Town,3,"15th A Cross Road, Yelahanka Satellite Town, Y...",MultiPolygon,"[[[[77.5909447, 13.0984219], [77.5922939, 13.0..."
3,Feature,51,Vijnanapura,4,"SP Naidu Layout 4th Cross Street, SP Naidu Lay...",MultiPolygon,"[[[[77.6768275, 13.0114668], [77.6769546, 13.0..."
4,Feature,53,Basavanapura,5,"Medahalli Kadugodi Road, Bharathi Nagar, Krish...",MultiPolygon,"[[[[77.728993, 13.0206055], [77.7299353, 13.01..."

In [52]:
df.isnull().sum()

type                       0
properties.WARD_NO         0
properties.WARD_NAME       0
properties.MOVEMENT_ID     0
properties.DISPLAY_NAME    0
geometry.type              0
geometry.coordinates       0
dtype: int64

In [53]:
df_temp = df.apply(lambda col: col.map(str)) #fixing columns (containing lists or dicts )which cant be hashed for comparison by converting them to strings

In [54]:
df_temp.duplicated().sum()

np.int64(0)

In [55]:
print(df.dtypes)

type                       object
properties.WARD_NO         object
properties.WARD_NAME       object
properties.MOVEMENT_ID     object
properties.DISPLAY_NAME    object
geometry.type              object
geometry.coordinates       object
dtype: object

In [56]:
print(df.columns.tolist())

['type', 'properties.WARD_NO', 'properties.WARD_NAME', 'properties.MOVEMENT_ID', 'properties.DISPLAY_NAME', 'geometry.type', 'geometry.coordinates']

In [57]:
df['properties.WARD_NO'] = df['properties.WARD_NO'].astype(int)
df['properties.MOVEMENT_ID'] = df['properties.MOVEMENT_ID'].astype(int)

In [58]:
print(df.dtypes)

type                       object
properties.WARD_NO          int64
properties.WARD_NAME       object
properties.MOVEMENT_ID      int64
properties.DISPLAY_NAME    object
geometry.type              object
geometry.coordinates       object
dtype: object

In [59]:
df.head()

,type,properties.WARD_NO,properties.WARD_NAME,properties.MOVEMENT_ID,properties.DISPLAY_NAME,geometry.type,geometry.coordinates
0,Feature,2,Chowdeswari Ward,1,"Unnamed Road, Bengaluru",MultiPolygon,"[[[[77.5922939, 13.0971962], [77.5909447, 13.0..."
1,Feature,3,Atturu,2,"9th Cross Bhel Layout, Adityanagar, Vidyaranya...",MultiPolygon,"[[[[77.5686203, 13.1270495], [77.5706371, 13.1..."
2,Feature,4,Yelahanka Satellite Town,3,"15th A Cross Road, Yelahanka Satellite Town, Y...",MultiPolygon,"[[[[77.5909447, 13.0984219], [77.5922939, 13.0..."
3,Feature,51,Vijnanapura,4,"SP Naidu Layout 4th Cross Street, SP Naidu Lay...",MultiPolygon,"[[[[77.6768275, 13.0114668], [77.6769546, 13.0..."
4,Feature,53,Basavanapura,5,"Medahalli Kadugodi Road, Bharathi Nagar, Krish...",MultiPolygon,"[[[[77.728993, 13.0206055], [77.7299353, 13.01..."

In [60]:
df.rename(columns={
    'properties.WARD_NO': 'ward_id',
    'properties.WARD_NAME': 'ward_name',
    'properties.MOVEMENT_ID': 'movement_id',
    'properties.DISPLAY_NAME': 'address'
}, inplace=True)

print(df.columns.tolist())

['type', 'ward_id', 'ward_name', 'movement_id', 'address', 'geometry.type', 'geometry.coordinates']

In [61]:
df.head()

,type,ward_id,ward_name,movement_id,address,geometry.type,geometry.coordinates
0,Feature,2,Chowdeswari Ward,1,"Unnamed Road, Bengaluru",MultiPolygon,"[[[[77.5922939, 13.0971962], [77.5909447, 13.0..."
1,Feature,3,Atturu,2,"9th Cross Bhel Layout, Adityanagar, Vidyaranya...",MultiPolygon,"[[[[77.5686203, 13.1270495], [77.5706371, 13.1..."
2,Feature,4,Yelahanka Satellite Town,3,"15th A Cross Road, Yelahanka Satellite Town, Y...",MultiPolygon,"[[[[77.5909447, 13.0984219], [77.5922939, 13.0..."
3,Feature,51,Vijnanapura,4,"SP Naidu Layout 4th Cross Street, SP Naidu Lay...",MultiPolygon,"[[[[77.6768275, 13.0114668], [77.6769546, 13.0..."
4,Feature,53,Basavanapura,5,"Medahalli Kadugodi Road, Bharathi Nagar, Krish...",MultiPolygon,"[[[[77.728993, 13.0206055], [77.7299353, 13.01..."

In [62]:
print(df['geometry.type'].unique())

['MultiPolygon']

In [63]:
df.drop(columns=['geometry.type'], inplace=True)
print(df.columns.tolist())

['type', 'ward_id', 'ward_name', 'movement_id', 'address', 'geometry.coordinates']

In [64]:
df['ward_name'] = df['ward_name'].str.replace('.', '', regex=False)
df['address'] = df['address'].str.title()
df['address'] = df['address'].str.replace(r'^\d+\s', '', regex=True)
df['address'] = df['address'].str.replace('#', '', regex=False)
df['address'] = df['address'].str.replace("'", '', regex=False)

In [65]:
df.head()

,type,ward_id,ward_name,movement_id,address,geometry.coordinates
0,Feature,2,Chowdeswari Ward,1,"Unnamed Road, Bengaluru","[[[[77.5922939, 13.0971962], [77.5909447, 13.0..."
1,Feature,3,Atturu,2,"9Th Cross Bhel Layout, Adityanagar, Vidyaranya...","[[[[77.5686203, 13.1270495], [77.5706371, 13.1..."
2,Feature,4,Yelahanka Satellite Town,3,"15Th A Cross Road, Yelahanka Satellite Town, Y...","[[[[77.5909447, 13.0984219], [77.5922939, 13.0..."
3,Feature,51,Vijnanapura,4,"Sp Naidu Layout 4Th Cross Street, Sp Naidu Lay...","[[[[77.6768275, 13.0114668], [77.6769546, 13.0..."
4,Feature,53,Basavanapura,5,"Medahalli Kadugodi Road, Bharathi Nagar, Krish...","[[[[77.728993, 13.0206055], [77.7299353, 13.01..."

In [66]:
(df['ward_id'] == df['movement_id']).all()

np.False_

In [70]:
df.shape

(198, 6)