In [1]:
import pandas as pd

In [2]:
sample = pd.read_json('dataset.json')

In [3]:
sample

                  type                                           features
0    FeatureCollection  {'type': 'Feature', 'properties': {'WARD_NO': ...
1    FeatureCollection  {'type': 'Feature', 'properties': {'WARD_NO': ...
2    FeatureCollection  {'type': 'Feature', 'properties': {'WARD_NO': ...
3    FeatureCollection  {'type': 'Feature', 'properties': {'WARD_NO': ...
4    FeatureCollection  {'type': 'Feature', 'properties': {'WARD_NO': ...
..                 ...                                                ...
193  FeatureCollection  {'type': 'Feature', 'properties': {'WARD_NO': ...
194  FeatureCollection  {'type': 'Feature', 'properties': {'WARD_NO': ...
195  FeatureCollection  {'type': 'Feature', 'properties': {'WARD_NO': ...
196  FeatureCollection  {'type': 'Feature', 'properties': {'WARD_NO': ...
197  FeatureCollection  {'type': 'Feature', 'properties': {'WARD_NO': ...

[198 rows x 2 columns]

In [4]:
df = pd.json_normalize(sample['features'])

In [5]:
df.head(5)

,type,properties.WARD_NO,properties.WARD_NAME,properties.MOVEMENT_ID,properties.DISPLAY_NAME,geometry.type,geometry.coordinates
0,Feature,2,Chowdeswari Ward,1,"Unnamed Road, Bengaluru",MultiPolygon,"[[[[77.5922939, 13.0971962], [77.5909447, 13.0..."
1,Feature,3,Atturu,2,"9th Cross Bhel Layout, Adityanagar, Vidyaranya...",MultiPolygon,"[[[[77.5686203, 13.1270495], [77.5706371, 13.1..."
2,Feature,4,Yelahanka Satellite Town,3,"15th A Cross Road, Yelahanka Satellite Town, Y...",MultiPolygon,"[[[[77.5909447, 13.0984219], [77.5922939, 13.0..."
3,Feature,51,Vijnanapura,4,"SP Naidu Layout 4th Cross Street, SP Naidu Lay...",MultiPolygon,"[[[[77.6768275, 13.0114668], [77.6769546, 13.0..."
4,Feature,53,Basavanapura,5,"Medahalli Kadugodi Road, Bharathi Nagar, Krish...",MultiPolygon,"[[[[77.728993, 13.0206055], [77.7299353, 13.01..."

In [6]:
df.isnull().sum()

type                       0
properties.WARD_NO         0
properties.WARD_NAME       0
properties.MOVEMENT_ID     0
properties.DISPLAY_NAME    0
geometry.type              0
geometry.coordinates       0
dtype: int64

In [7]:
df_temp = df.apply(lambda col: col.map(str)) #fixing columns (containing lists or dicts )which cant be hashed for comparison by converting them to strings

In [8]:
df_temp.duplicated().sum()

np.int64(0)

In [9]:
print(df.dtypes)

type                       object
properties.WARD_NO         object
properties.WARD_NAME       object
properties.MOVEMENT_ID     object
properties.DISPLAY_NAME    object
geometry.type              object
geometry.coordinates       object
dtype: object

In [10]:
print(df.columns.tolist())

['type', 'properties.WARD_NO', 'properties.WARD_NAME', 'properties.MOVEMENT_ID', 'properties.DISPLAY_NAME', 'geometry.type', 'geometry.coordinates']

In [11]:
df['properties.WARD_NO'] = df['properties.WARD_NO'].astype(int)
df['properties.MOVEMENT_ID'] = df['properties.MOVEMENT_ID'].astype(int)

In [12]:
print(df.dtypes)

type                       object
properties.WARD_NO          int64
properties.WARD_NAME       object
properties.MOVEMENT_ID      int64
properties.DISPLAY_NAME    object
geometry.type              object
geometry.coordinates       object
dtype: object

In [13]:
df.head()

,type,properties.WARD_NO,properties.WARD_NAME,properties.MOVEMENT_ID,properties.DISPLAY_NAME,geometry.type,geometry.coordinates
0,Feature,2,Chowdeswari Ward,1,"Unnamed Road, Bengaluru",MultiPolygon,"[[[[77.5922939, 13.0971962], [77.5909447, 13.0..."
1,Feature,3,Atturu,2,"9th Cross Bhel Layout, Adityanagar, Vidyaranya...",MultiPolygon,"[[[[77.5686203, 13.1270495], [77.5706371, 13.1..."
2,Feature,4,Yelahanka Satellite Town,3,"15th A Cross Road, Yelahanka Satellite Town, Y...",MultiPolygon,"[[[[77.5909447, 13.0984219], [77.5922939, 13.0..."
3,Feature,51,Vijnanapura,4,"SP Naidu Layout 4th Cross Street, SP Naidu Lay...",MultiPolygon,"[[[[77.6768275, 13.0114668], [77.6769546, 13.0..."
4,Feature,53,Basavanapura,5,"Medahalli Kadugodi Road, Bharathi Nagar, Krish...",MultiPolygon,"[[[[77.728993, 13.0206055], [77.7299353, 13.01..."

In [14]:
df.rename(columns={
    'properties.WARD_NO': 'ward_id',
    'properties.WARD_NAME': 'ward_name',
    'properties.MOVEMENT_ID': 'movement_id',
    'properties.DISPLAY_NAME': 'address'
}, inplace=True)

print(df.columns.tolist())

['type', 'ward_id', 'ward_name', 'movement_id', 'address', 'geometry.type', 'geometry.coordinates']

In [15]:
df.head()

,type,ward_id,ward_name,movement_id,address,geometry.type,geometry.coordinates
0,Feature,2,Chowdeswari Ward,1,"Unnamed Road, Bengaluru",MultiPolygon,"[[[[77.5922939, 13.0971962], [77.5909447, 13.0..."
1,Feature,3,Atturu,2,"9th Cross Bhel Layout, Adityanagar, Vidyaranya...",MultiPolygon,"[[[[77.5686203, 13.1270495], [77.5706371, 13.1..."
2,Feature,4,Yelahanka Satellite Town,3,"15th A Cross Road, Yelahanka Satellite Town, Y...",MultiPolygon,"[[[[77.5909447, 13.0984219], [77.5922939, 13.0..."
3,Feature,51,Vijnanapura,4,"SP Naidu Layout 4th Cross Street, SP Naidu Lay...",MultiPolygon,"[[[[77.6768275, 13.0114668], [77.6769546, 13.0..."
4,Feature,53,Basavanapura,5,"Medahalli Kadugodi Road, Bharathi Nagar, Krish...",MultiPolygon,"[[[[77.728993, 13.0206055], [77.7299353, 13.01..."

In [16]:
print(df['geometry.type'].unique())

['MultiPolygon']

In [17]:
df.drop(columns=['geometry.type'], inplace=True)
print(df.columns.tolist())

['type', 'ward_id', 'ward_name', 'movement_id', 'address', 'geometry.coordinates']

In [18]:
df['ward_name'] = df['ward_name'].str.replace('.', '', regex=False)
df['address'] = df['address'].str.title()
df['address'] = df['address'].str.replace(r'^\d+\s', '', regex=True)
df['address'] = df['address'].str.replace('#', '', regex=False)
df['address'] = df['address'].str.replace("'", '', regex=False)

In [19]:
df.head()

,type,ward_id,ward_name,movement_id,address,geometry.coordinates
0,Feature,2,Chowdeswari Ward,1,"Unnamed Road, Bengaluru","[[[[77.5922939, 13.0971962], [77.5909447, 13.0..."
1,Feature,3,Atturu,2,"9Th Cross Bhel Layout, Adityanagar, Vidyaranya...","[[[[77.5686203, 13.1270495], [77.5706371, 13.1..."
2,Feature,4,Yelahanka Satellite Town,3,"15Th A Cross Road, Yelahanka Satellite Town, Y...","[[[[77.5909447, 13.0984219], [77.5922939, 13.0..."
3,Feature,51,Vijnanapura,4,"Sp Naidu Layout 4Th Cross Street, Sp Naidu Lay...","[[[[77.6768275, 13.0114668], [77.6769546, 13.0..."
4,Feature,53,Basavanapura,5,"Medahalli Kadugodi Road, Bharathi Nagar, Krish...","[[[[77.728993, 13.0206055], [77.7299353, 13.01..."

In [20]:
(df['ward_id'] == df['movement_id']).all()

np.False_

In [21]:
df.shape

(198, 6)

In [22]:
from shapely.geometry import shape
import json

with open('dataset.json') as f:
    data = json.load(f)

In [23]:
df['area'] = [shape(f['geometry']).area for f in data['features']]

In [24]:
df['mapped_regions'] = df['address'].str.split(',').str.len()

In [25]:
df.head()

,type,ward_id,ward_name,movement_id,address,geometry.coordinates,area,mapped_regions
0,Feature,2,Chowdeswari Ward,1,"Unnamed Road, Bengaluru","[[[[77.5922939, 13.0971962], [77.5909447, 13.0...",0.000639,2
1,Feature,3,Atturu,2,"9Th Cross Bhel Layout, Adityanagar, Vidyaranya...","[[[[77.5686203, 13.1270495], [77.5706371, 13.1...",0.000824,4
2,Feature,4,Yelahanka Satellite Town,3,"15Th A Cross Road, Yelahanka Satellite Town, Y...","[[[[77.5909447, 13.0984219], [77.5922939, 13.0...",0.000408,4
3,Feature,51,Vijnanapura,4,"Sp Naidu Layout 4Th Cross Street, Sp Naidu Lay...","[[[[77.6768275, 13.0114668], [77.6769546, 13.0...",0.000171,4
4,Feature,53,Basavanapura,5,"Medahalli Kadugodi Road, Bharathi Nagar, Krish...","[[[[77.728993, 13.0206055], [77.7299353, 13.01...",0.000536,4

In [26]:
df['latitude'] = [shape(f['geometry']).centroid.y for f in data['features']]
df['longitude'] = [shape(f['geometry']).centroid.x for f in data['features']]

In [27]:
df.head()

,type,ward_id,ward_name,movement_id,address,geometry.coordinates,area,mapped_regions,latitude,longitude
0,Feature,2,Chowdeswari Ward,1,"Unnamed Road, Bengaluru","[[[[77.5922939, 13.0971962], [77.5909447, 13.0...",0.000639,2,13.121709,77.580422
1,Feature,3,Atturu,2,"9Th Cross Bhel Layout, Adityanagar, Vidyaranya...","[[[[77.5686203, 13.1270495], [77.5706371, 13.1...",0.000824,4,13.102805,77.560038
2,Feature,4,Yelahanka Satellite Town,3,"15Th A Cross Road, Yelahanka Satellite Town, Y...","[[[[77.5909447, 13.0984219], [77.5922939, 13.0...",0.000408,4,13.090987,77.583925
3,Feature,51,Vijnanapura,4,"Sp Naidu Layout 4Th Cross Street, Sp Naidu Lay...","[[[[77.6768275, 13.0114668], [77.6769546, 13.0...",0.000171,4,13.006063,77.669565
4,Feature,53,Basavanapura,5,"Medahalli Kadugodi Road, Bharathi Nagar, Krish...","[[[[77.728993, 13.0206055], [77.7299353, 13.01...",0.000536,4,13.016847,77.715456

In [28]:
df.drop(columns=['type', 'movement_id', 'geometry.coordinates'], inplace=True)

In [29]:
print(df.columns.tolist())

['ward_id', 'ward_name', 'address', 'area', 'mapped_regions', 'latitude', 'longitude']

In [30]:
print(df.shape)

(198, 7)

In [32]:
print(df['area'].describe())

count    198.000000
mean       0.000299
std        0.000399
min        0.000027
25%        0.000079
50%        0.000139
75%        0.000348
max        0.002369
Name: area, dtype: float64

In [39]:
print(df[['ward_name', 'area']].sort_values('area', ascending=False).head(10))

               ward_name      area
197          Hemmigepura  0.002369
164             Varthuru  0.002233
165           Bellanduru  0.002206
12               Jakkuru  0.002016
181                Begur  0.001576
195             Horamavu  0.001474
5                   Hudi  0.001282
19     Dodda Bidarakallu  0.001090
168              Hagadur  0.001063
187  Jnana Bharathi ward  0.001018

In [41]:
print(df[['ward_name', 'area']].sort_values('area').head(10))

              ward_name      area
126      Padarayanapura  0.000027
118  Kempapura Agrahara  0.000029
129      Chalavadipalya  0.000032
86        Shivaji Nagar  0.000036
128           Rayapuram  0.000037
106     Dayananda Nagar  0.000037
62     Muneshwara Nagar  0.000040
92           Nilasandra  0.000044
107       Prakash Nagar  0.000047
127  Jagajivanaramnagar  0.000053

In [33]:
print(df['mapped_regions'].describe())

count    198.000000
mean       4.353535
std        0.764878
min        2.000000
25%        4.000000
50%        4.000000
75%        5.000000
max        6.000000
Name: mapped_regions, dtype: float64

In [40]:
print(df['mapped_regions'].value_counts().sort_index())

mapped_regions
2     3
3    17
4    94
5    75
6     9
Name: count, dtype: int64

In [36]:
print(df[['ward_name', 'mapped_regions']].sort_values('mapped_regions', ascending=False).head(10))

              ward_name  mapped_regions
14      Byatarayanapura               6
7        A Narayanapura               6
67           HBR Layout               6
147  Ganesh Mandir ward               6
159         Jakkasandra               6
77     New Tippasandara               6
169      Dodda Nekkundi               6
161   Pattabhiram Nagar               6
146       Hosakerehalli               6
54              Hebbala               5

In [47]:
import folium
import geopandas as gpd
import json

gdf = gpd.read_file('dataset.json')


gdf['area'] = df['area'].values
gdf['mapped_regions'] = df['mapped_regions'].values
gdf['latitude'] = df['latitude'].values
gdf['longitude'] = df['longitude'].values


m = folium.Map(location=[12.97, 77.59], zoom_start=11)


def get_color(area):
    if area > 0.001:
        return 'red'
    elif area > 0.0005:
        return 'orange'
    elif area > 0.0002:
        return 'yellow'
    else:
        return 'green'


for _, row in gdf.iterrows():
    folium.GeoJson(
        row['geometry'].__geo_interface__,  
        style_function=lambda x, area=row['area']: {
            'fillColor': get_color(area),
            'color': 'black',
            'weight': 1,
            'fillOpacity': 0.6
        },
        tooltip=f"Ward: {row['WARD_NAME']} | ID: {row['WARD_NO']} | Area: {row['area']:.6f} | Mapped Regions: {row['mapped_regions']}"  # ← fix: simple string tooltip
    ).add_to(m)


top10_area = df.nlargest(10, 'area')
for _, row in top10_area.iterrows():
    folium.Marker(
        location=[row['latitude'], row['longitude']],
        popup=folium.Popup(
            f"<b>{row['ward_name']}</b><br>Area: {row['area']:.6f}<br>Mapped Regions: {row['mapped_regions']}",
            max_width=200
        ),
        icon=folium.Icon(color='red', icon='info-sign')
    ).add_to(m)


legend_html = """
<div style="position: fixed; bottom: 30px; left: 30px; z-index: 1000;
     background-color: white; padding: 10px; border-radius: 5px;
     border: 2px solid grey; font-size: 14px;">
     <b>Ward Area Size</b><br>
     <i style="background:red;width:12px;height:12px;display:inline-block"></i> Largest (>0.001)<br>
     <i style="background:orange;width:12px;height:12px;display:inline-block"></i> Medium-Large (>0.0005)<br>
     <i style="background:yellow;width:12px;height:12px;display:inline-block"></i> Medium (>0.0002)<br>
     <i style="background:green;width:12px;height:12px;display:inline-block"></i> Smallest (<0.0002)<br>
</div>
"""
m.get_root().html.add_child(folium.Element(legend_html))


m.save('bengaluru_wards_map.html')
print("Map saved!")

Map saved!